# Generated by Django 5.0.6 on 2024-06-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=10)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('light', models.FloatField()),
                ('snd', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
