# Generated by Django 5.0.6 on 2024-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=100)),
                ("event_name", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="loc",
            field=models.CharField(max_length=50),
        ),
    ]
