# Generated by Django 5.0.6 on 2024-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_data", "0002_venueevent_alter_sensordata_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="loc",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="node_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
