# Generated by Django 3.2.6 on 2024-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_alter_sensordata_loc_alter_sensordata_node_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
